name: "测试"
#dsafghj
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Find and configure fastest Ubuntu mirror
        run: |
          # 安装 netselect（如果系统默认没有）
          sudo apt update && sudo apt install netselect -y
          # 获取镜像列表并测试，取第一个（最快）的镜像
          FASTEST_MIRROR=$(netselect -s 1 -t 20 $(wget -qO - mirrors.ubuntu.com/mirrors.txt) | awk '{print $2}')
          echo "Fastest mirror found: $FASTEST_MIRROR"
          # 备份原来的源配置文件（Ubuntu 24.04 默认是 /etc/apt/sources.list.d/ubuntu.sources）
          sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.backup
          # 使用找到的最快镜像替换原来的官方镜像（注意：需要根据 Ubuntu 版本代号修改，这里是 noble）
          sudo sed -i "s|http://archive.ubuntu.com/ubuntu/|http://$FASTEST_MIRROR/ubuntu/|g" /etc/apt/sources.list.d/ubuntu.sources
          sudo sed -i "s|http://security.ubuntu.com/ubuntu/|http://$FASTEST_MIRROR/ubuntu/|g" /etc/apt/sources.list.d/ubuntu.sources
          # 更新软件列表
          sudo apt update
